### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by hicham-alsayed-ahmad** [akosbrachna/gps_tracker#1]
Good Day,

I have followed all the steps you mention on the board,

after that i get this error :
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by akosbrachna** [comment]
Good evening,

Thank you for your feedback. There is a problem in the .htaccess file in the root folder.
These lines should be removed:

AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/css
AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript

Updated the file here in github too. I tested it locally and it works for me. I use xampp as a server environment.
If you have any more questions or problems let me know.

Regards,
Akos

**Comment by hicham-alsayed-ahmad** [comment]
thank you so much,
when I trying to use mysql I get this error:`Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /Applications/Ampps/www/gps_tracker/system/database/drivers/mysql/mysql_driver.php:73 Stack trace: #0 /Applications/Ampps/www/gps_tracker/system/database/DB_driver.php(115): CI_DB_mysql_driver->db_connect() #1 /Applications/Ampps/www/gps_tracker/system/database/DB.php(148): CI_DB_driver->initialize() #2 /Applications/Ampps/www/gps_tracker/system/core/Loader.php(338): DB(Array, NULL) #3 /Applications/Ampps/www/gps_tracker/application/controllers/database/tables.php(10): CI_Loader->database('default', true) #4 /Applications/Ampps/www/gps_tracker/system/core/CodeIgniter.php(308): Tables->__construct() #5 /Applications/AMPPS/www/gps_tracker/index.php(202): require_once('/Applications/A...') #6 {main} thrown in /Applications/Ampps/www/gps_tracker/system/database/drivers/mysql/mysql_driver.php on line 73`
when I change it to mysqli I get this error `A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'member varchar(255) NOT NULL, category varchar(255) NOT NULL, permission varch' at line 4

CREATE TABLE IF NOT EXISTS `contacts` ( id int(11) NOT NULL AUTO_INCREMENT, owner varchar(255) NOT NULL, member varchar(255) NOT NULL, category varchar(255) NOT NULL, permission varchar(255) NOT NULL DEFAULT 'enabled', status varchar(255) NOT NULL DEFAULT 'visible', joined_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY `id` (`id`) ) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

Filename: /Applications/Ampps/www/gps_tracker/controllers/database/tables.php

Line Number: 61`

**Comment by akosbrachna** [comment]
Good evening :)
I assume you use a newer version of apache, php, mysql. 
At the time i created the project i used xampp 5.6.15 which can be accessed here:
https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/5.6.15/
If you try this version and still have a problem, let me know. I hope this will solve the problem for you.
Unfortunately i'm too busy to maintain and upgrade the project to newer versions.

**Comment by hicham-alsayed-ahmad** [comment]
thank you again ,
I am using MacBook Pro and I don't have xampp ,

I'm using Ampps 

thanks again .

**Comment by akosbrachna** [comment]
You're welcome :)
Here is a Mac OS version of xampp 5.6.15:
https://sourceforge.net/projects/xampp/files/XAMPP%20Mac%20OS%20X/5.6.15/
I hope this will help.

**Comment by hicham-alsayed-ahmad** [comment]
thanks a lot , 
awesome work !

**Comment by akosbrachna** [comment]
Thanks for your feedback and help to correct my mistakes.
